# Generated by Django 5.1 on 2024-09-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.IntegerField()),
                ('item_cost', models.IntegerField()),
                ('item_source', models.CharField(max_length=300)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
