# Generated by Django 5.1 on 2024-09-12 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_reserve_branch_reserve_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_notes', models.CharField(max_length=1000)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.patient')),
            ],
        ),
    ]
