# Generated by Django 5.1 on 2024-09-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_reserve_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
