# Generated by Django 5.1 on 2024-09-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='birth',
        ),
    ]
