# Generated by Django 5.1 on 2024-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_service_remove_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='service',
            field=models.CharField(choices=[('Service', 'Service'), ('Consultation', 'Consultation'), ('Retouch', 'Retouch')], default='Service type', max_length=50),
        ),
    ]
