# Generated by Django 5.1 on 2024-09-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_reserve_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='company_source',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='item',
        ),
        migrations.RemoveField(
            model_name='medical_history',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='services',
        ),
        migrations.RemoveField(
            model_name='paymentservice',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentservice',
            name='service',
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Medical_History',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentService',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
