# Generated by Django 5.1 on 2024-09-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_companies_service_inventory_invoice_medical_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentservice',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentinventory',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentinventory',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='paymentservice',
            name='service',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentInventory',
        ),
        migrations.DeleteModel(
            name='PaymentService',
        ),
    ]
