# Generated by Django 5.1 on 2024-09-21 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_remove_paymentservice_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('method', models.CharField(choices=[('INSTAPAY', 'INSTAPAY'), ('CASH', 'CASH'), ('CREDIT CARD', 'CREDIT CARD')], default='CASH', max_length=100)),
                ('service_quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('service_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('inventory_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.inventory')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.patient')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.service')),
            ],
        ),
    ]
