# Generated by Django 5.1 on 2024-09-29 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_activitylog_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
