# Generated by Django 5.1 on 2024-10-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_paymentinventory_price_at_time_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='patient',
            field=models.CharField(max_length=20),
        ),
    ]
