# Generated by Django 5.1 on 2024-10-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_alter_payment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='Branch',
            field=models.CharField(choices=[('EL_Mohandsen', 'EL_Mohandsen'), ('5th_sattelment', '5th_sattelment'), ('Naser_city', 'Naser_city')], default='Branch', max_length=50),
        ),
    ]
