# Generated by Django 5.1 on 2024-10-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_dates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Immediate', 'Immediate Payment'), ('Deferred', 'Deferred Payment')], default='Immediate', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
