# Generated by Django 5.1 on 2024-10-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_invoice_due_dates_invoice_is_fully_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Branch',
            field=models.CharField(choices=[('EL_Mohandsen', 'EL_Mohandsen'), ('5th_sattelment', '5th_sattelment'), ('Naser_city', 'Naser_city')], default='Branch', max_length=50),
        ),
    ]
