# Generated by Django 5.1 on 2024-09-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_reserve_delete_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reserve',
        ),
    ]
