# Generated by Django 5.1 on 2024-09-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-create_at']},
        ),
    ]
