# Generated by Django 5.1 on 2024-09-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_companies_inventory_invoice_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
