# Generated by Django 5.1 on 2024-09-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
