# Generated by Django 5.1 on 2024-10-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_alter_reserve_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('INSTAPAY', 'INSTAPAY'), ('CASH', 'CASH'), ('CREDIT CARD', 'CREDIT CARD'), ('E_WALLET', 'E_WALLET')], default='CASH', max_length=100),
        ),
    ]
