# Generated by Django 5.1 on 2024-12-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_alter_reserve_phone_remove_reserve_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='service_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
