# Generated by Django 5.1 on 2024-12-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_reserve_service_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='name',
        ),
        migrations.AddField(
            model_name='reserve',
            name='patient_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='service',
            field=models.ManyToManyField(choices=[('Service', 'Service'), ('Consultation', 'Consultation'), ('Retouch', 'Retouch')], related_name='reserves', to='webapp.service'),
        ),
    ]
