# Generated by Django 5.1 on 2024-12-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0047_reserve_notes_alter_reserve_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
