# Generated by Django 5.1 on 2024-12-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_delete_category_delete_record_patient_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='patient',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='service',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='type',
            field=models.CharField(choices=[('old', 'old'), ('new', 'new')], default='old', max_length=100),
        ),
        migrations.AddField(
            model_name='reserve',
            name='service',
            field=models.ManyToManyField(related_name='reserves', to='webapp.service'),
        ),
    ]
