# Generated by Django 5.1 on 2024-12-09 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_alter_payment_patient_remove_reserve_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='service',
            new_name='services',
        ),
    ]
