# Generated by Django 5.1 on 2024-12-09 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0052_rename_service_reserve_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='services',
        ),
        migrations.CreateModel(
            name='ReservationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_services', to='webapp.reserve')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.service')),
            ],
        ),
    ]
