# Generated by Django 5.1 on 2024-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0055_remove_payment_offer_alter_paymentinventory_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=250)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Enter the discount percentage (e.g., 10 for 10%)', max_digits=5)),
            ],
        ),
    ]
