# Generated by Django 5.1 on 2024-12-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0058_invoice_installments_count_invoice_remaining_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='purchase_date',
            new_name='create_at',
        ),
    ]
