# Generated by Django 5.1 on 2024-12-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0059_rename_purchase_date_invoice_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
