# Generated by Django 5.1 on 2024-12-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0060_rename_create_at_invoice_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='reserve',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
