# Generated by Django 5.1 on 2024-12-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0063_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
