# Generated by Django 5.1 on 2024-12-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0064_inventory_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.offers'),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Pay', 'Pay'), ('Refund', 'Refund')], default='Pay', max_length=50),
        ),
    ]
