# Generated by Django 5.1 on 2024-12-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0065_payment_offer_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the fixed discount amount (e.g., 100 for 100 EGP). Leave blank if using percentage.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Start date and time for the offer', null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='valid_to',
            field=models.DateTimeField(blank=True, help_text='End date and time for the offer', null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the discount percentage (e.g., 10 for 10%). Leave blank if using a fixed amount.', max_digits=5, null=True),
        ),
    ]
