# Generated by Django 5.1 on 2024-12-30 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0066_offers_discount_amount_offers_valid_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='offer_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='payment',
            name='inventory',
            field=models.ManyToManyField(through='webapp.PaymentInventory', to='webapp.inventory'),
        ),
        migrations.AddField(
            model_name='payment',
            name='services',
            field=models.ManyToManyField(through='webapp.PaymentService', to='webapp.service'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='valid_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='offers',
            name='valid_to',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='OfferInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.inventory')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.offers')),
            ],
        ),
        migrations.AddField(
            model_name='offers',
            name='inventory',
            field=models.ManyToManyField(through='webapp.OfferInventory', to='webapp.inventory'),
        ),
        migrations.CreateModel(
            name='OfferService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.offers')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.service')),
            ],
        ),
        migrations.AddField(
            model_name='offers',
            name='services',
            field=models.ManyToManyField(through='webapp.OfferService', to='webapp.service'),
        ),
    ]
