# Generated by Django 5.1 on 2025-01-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0068_remove_payment_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
