# Generated by Django 5.1 on 2025-01-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0070_alter_payment_options_finance_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='total_amount',
        ),
    ]
