# Generated by Django 5.1 on 2025-01-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0072_finance_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='total_amount',
        ),
    ]
