# Generated by Django 5.1 on 2025-01-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0073_remove_finance_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finance',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_visit',
        ),
    ]
