# Generated by Django 5.1 on 2025-01-11 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0075_useditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.inventory')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_inventories', to='webapp.reserve')),
            ],
        ),
    ]
