# Generated by Django 5.1 on 2025-01-15 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0076_reservationinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
