# Generated by Django 5.1 on 2025-01-15 12:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0077_payment_date_alter_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
