# Generated by Django 4.2.9 on 2025-01-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0078_finance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='services',
            field=models.JSONField(default=list),
        ),
    ]
