# Generated by Django 4.2.9 on 2025-01-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0079_reserve_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='services',
            field=models.JSONField(choices=[('SKINBOOSTER', 'Skinbooster'), ('FILLER', 'Filler'), ('DISSOLVING_FILLER', 'Dissolving Filler'), ('BOTOX', 'Botox'), ('RETOUCH', 'Retouch'), ('CONSULTATION', 'Consultation'), ('DERMA_PEN', 'Derma Pen'), ('LIP_FILLER', 'Lip Filler'), ('MESOTHERAPY', 'Mesotherapy')], default=list),
        ),
    ]
